### ISSUE TITLE
Document removing DB/ES profile entries

### ISSUE THREAD

**Issue by geoffturk** [MurmurationsNetwork/MurmurationsLibrary#122]
The following deprecated schemas from the test library have entries that eventually need to be removed from Mongo and Elasticsearch:

- `person_schema-v.0.1.0` - 100 posted, 0 deleted
- `person_schema-v.0.2.0` - 1 posted, 0 deleted

**Comment by vthwang** [comment]
# Data Deletion Process in ElasticSearch and MongoDB
## Step 1: Define the Query in ElasticSearch
Before proceeding with data deletion, we need to find the data which we want to delete in the search queries. Here are two scenarios for defining the search query based on linked_schemas:
### Scenario 1: Deleting Nodes Containing a Specific Schema
To delete nodes that contain a specific schema (e.g., test_schema-v2.1.0), use the following search query. This query identifies all nodes linked to the specified schema.
```
GET /nodes/_search
{
  "query": {
    "match": {
      "linked_schemas": "test_schema-v2.1.0"
    }
  },
  "_source": ["profile_url"]
}
```
### Scenario 2: Deleting Nodes Containing Only One Specific Schema
If the requirement is to delete nodes that contain only one schema, and that schema matches the specified one (e.g., test_schema-v2.1.0), use the below search query. This query filters the nodes to ensure that only those with exactly one linked schema matching the query are showed.
```
GET /nodes/_search
{
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "linked_schemas": "test_schema-v2.1.0"
          }
        }
      ],
      "filter": [
        {
          "script": {
            "script": {
              "source": "doc['linked_schemas'].size() == 1",
              "lang": "painless"
            }
          }
        }
      ]
    }
  },
  "_source": ["profile_url"]
}
```

**Comment by vthwang** [comment]
Transferred to the "Murmurations Services" documents folder.
